// ALERT DISPATCH STATES
export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'

export const LOAD_DOCUMENTS_SUCCESS = 'LOAD_DOCUMENTS_SUCCESS'
export const LOAD_DOCUMENTS_FAIL = 'LOAD_DOCUMENTS_FAIL'