# Generated by Django 4.0.5 on 2022-06-15 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sun', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('asking_pr', models.SmallIntegerField()),
                ('water_dam', models.BooleanField()),
                ('dam_note', models.TextField()),
                ('est_value', models.SmallIntegerField()),
                ('location', models.TextField()),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sun.region')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('buyer', models.BooleanField()),
                ('seller', models.BooleanField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sun.property')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sun.region')),
            ],
        ),
    ]
