# Generated by Django 4.0.5 on 2022-06-15 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sun', '0002_property_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='user_id',
            new_name='user',
        ),
    ]
