export const GET_CLIENTS = 'GET_CLIENTS'
export const GET_CLIENT_DETAIL = 'GET_CLIENT_DETAIL'
export const CREATE_CLIENT = 'CREATE_CLIENT'
export const DESTROY_CLIENT = 'DESTROY_CLIENT'

export const GET_PROPERTIES = 'GET_PROPERTIES'
export const GET_PROPERTY_DETAIL = 'GET_PROPERTY_DETAIL'
export const CREATE_PROPERTY = 'CREATE_PROPERTY'
export const DESTROY_PROPERTY = 'DESTROY_PROPERTY'

export const GET_NOTES = 'GET_NOTES'
export const GET_NOTE_DETAIL = 'GET_NOTE_DETAIL'
export const CREATE_NOTE = 'CREATE_NOTE'
export const DESTROY_NOTE = 'DESTROY_NOTE'

export const GET_REGIONS = 'GET_REGIONS'
export const GET_REGION_DETAIL = 'GET_REGION_DETAIL'
export const CREATE_REGION = 'CREATE_REGION'
export const DESTROY_REGION = 'DESTROY_REGION'